In [ ]:
!pip install mlxtend

:

In [ ]:
import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
data=pd.read_csv('Market_Basket_Optimisation.csv')
data.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data['ColumnA']=data[data.columns[0:]].apply(
    lambda x: ',' .join(x.dropna().astype(str)),
    axis=1
)

df=data.ColumnA
df=pd.DataFrame(data=df.values,columns=['ColumnA'])
print(df.shape)
print(df)

data_hot_encoded=df.drop('ColumnA',1).join(df.ColumnA.str.get_dummies(','))
data_hot_encoded.shape

(7500, 1)
                                                ColumnA
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

C:\Users\Yogita\AppData\Local\Temp\ipykernel_9540\1643710905.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data_hot_encoded=df.drop('ColumnA',1).join(df.ColumnA.str.get_dummies(','))

(7500, 120)

In [4]:
data_hot_encoded.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
itemsets=apriori(data_hot_encoded,use_colnames=True, min_support=0.05)
itemsets=itemsets.sort_values(by="support",ascending=False)

frequent_itemsets=apriori(data_hot_encoded,min_support=0.05,use_colnames=True)
frequent_itemsets['length']=frequent_itemsets['itemsets'].apply(lambda x:len(x))
frequent_itemsets

C:\Python311\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
C:\Python311\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                    itemsets  length
0   0.087200                   (burgers)       1
1   0.081067                      (cake)       1
2   0.060000                   (chicken)       1
3   0.163867                 (chocolate)       1
4   0.080400                   (cookies)       1
5   0.051067               (cooking oil)       1
6   0.179733                      (eggs)       1
7   0.079333                  (escalope)       1
8   0.170933              (french fries)       1
9   0.063200           (frozen smoothie)       1
10  0.095333         (frozen vegetables)       1
11  0.052400             (grated cheese)       1
12  0.132000                 (green tea)       1
13  0.098267               (ground beef)       1
14  0.076400            (low fat yogurt)       1
15  0.129600                      (milk)       1
16  0.238267             (mineral water)       1
17  0.065733                 (olive oil)       1
18  0.095067                  (pancakes)       1
19  0.071333                    (shrimp)       1
20  0.050533                      (soup)       1
21  0.174133                 (spaghetti)       1
22  0.068400                  (tomatoes)       1
23  0.062533                    (turkey)       1
24  0.058533          (whole wheat rice)       1
25  0.052667  (mineral water, chocolate)       2
26  0.050933       (mineral water, eggs)       2
27  0.059733  (mineral water, spaghetti)       2

In [6]:
rules=association_rules(itemsets,metric='lift',min_threshold=1)

rules=rules.sort_values(by="lift" , ascending=False)
print('_'*20, 'association rules','_'*20)
print(rules)

____________________ association rules ____________________
       antecedents      consequents  antecedent support  consequent support  \
1      (spaghetti)  (mineral water)            0.174133            0.238267
0  (mineral water)      (spaghetti)            0.238267            0.174133
2  (mineral water)      (chocolate)            0.238267            0.163867
3      (chocolate)  (mineral water)            0.163867            0.238267
4  (mineral water)           (eggs)            0.238267            0.179733
5           (eggs)  (mineral water)            0.179733            0.238267

    support  confidence      lift  leverage  conviction  zhangs_metric
1  0.059733    0.343032  1.439698  0.018243    1.159468       0.369806
0  0.059733    0.250699  1.439698  0.018243    1.102184       0.400941
2  0.052667    0.221041  1.348907  0.013623    1.073398       0.339566
3  0.052667    0.321400  1.348907  0.013623    1.122506       0.309351
4  0.050933    0.213766  1.189351  0.008109    1.043286       0.209004
5  0.050933    0.283383  1.189351  0.008109    1.062957       0.194090